import Head from "next/head";
import handleLogout from "../../../lib/handlelogout";

export default function Home({ user }) {
  return (
    <>
      <div className="container">
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create-next-app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <main>
          <h1>
            Welcome to <a href="https://nextjs.org">Next.js!</a>
          </h1>
          <p className="description">
            Get started by editing <code>pages/index.js</code>
          </p>
          {user && (
            <div>
              <h2>User Info: </h2>
              <p>
                <strong>Email: </strong>
                {user?.email}
              </p>
              <p>
                <strong>Display Name: </strong>
                {user?.displayName}
              </p>
              <p>
                <strong>Photo URL: </strong>
                {user.photoURL ? (
                  <img src={user.photoURL} alt="User Photo" />
                ) : (
                  <img
                    src="https://www.gravatar.com/avatar/205e460b479e2e5b48aec07710c08d50?s=200"
                    alt={user?.displayName}
                  />
                )}
              </p>
              <p>
                <strong>User ID: </strong>
                {user?.uid}
              </p>
              <p>
                <strong>Email Verified: </strong>
                {user.emailVerified ? "Yes" : "No"}
              </p>
              <p>
                <strong>Provider ID: </strong>
                {user?.providerData[0].providerId}
              </p>
              <p>
                <strong>Provider UID: </strong>
                {user?.providerData[0].uid}
              </p>
              <p>
                <strong>Provider Display Name: </strong>
                {user?.providerData[0].displayName}
              </p>
              <hr />

              <p>Email: {user.email}</p>

              <p>User is LoggedIn✅</p>
            </div>
          )}
          <button onClick={handleLogout}>Logout</button>
          <hr />
        </main>
      </div>
    </>
  );
}
