import Head from "next/head";
import Image from "next/image";
import { useState } from "react";
import aathu from "../lib/aathu";
import handleLogout from "../lib/handlelogout";
import styles from "../styles/Home.module.css";

export default function Home({ user }) {
  console.log(user?.photoURL);
  // const [loading, setLoading] = useState(true);
  // const { user, isLoggedIn } = aathu();

  // if (!isLoggedIn) {
  //   if (loading) {
  //     return <p>Loading...</p>;
  //   }
  //   return (
  //     <div>
  //       <h1>Please login to see the user info</h1>
  //     </div>
  //   );
  // }
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <p className={styles.description}>
          Get started by editing{" "}
          <code className={styles.code}>pages/index.js</code>
        </p>

        <div className={styles.grid}>
          <a href="https://nextjs.org/docs" className={styles.card}>
            <h2>Documentation &rarr;</h2>
            <p>Find in-depth information about Next.js features and API.</p>
          </a>

          <a href="https://nextjs.org/learn" className={styles.card}>
            <h2>Learn &rarr;</h2>
            <p>Learn about Next.js in an interactive course with quizzes!</p>
          </a>

          <a
            href="https://github.com/vercel/next.js/tree/canary/examples"
            className={styles.card}
          >
            <h2>Examples &rarr;</h2>
            <p>Discover and deploy boilerplate example Next.js projects.</p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
          >
            <h2>Deploy &rarr;</h2>
            <p>
              Instantly deploy your Next.js site to a public URL with Vercel.
            </p>
          </a>
          <a className={styles.card}>
            <h2>User &rarr;</h2>
            <p>
              <>
                {user && (
                  <div>
                    <h2>User Info: </h2>
                    <strong>Email: </strong>
                    {user?.email}
                    <br />
                    <strong>Display Name: </strong>
                    {user?.displayName}
                    <br />
                    <strong>Photo URL: </strong>
                    {user.photoURL ? (
                      <img
                        src={user.photoURL}
                        alt="User Photo"
                        width={200}
                        height={200}
                      />
                    ) : (
                      <img
                        src="https://cdn.pixabay.com/photo/2015/10/05/22/37/blank-profile-picture-973460_640.png"
                        alt="User Photo"
                        width={200}
                        height={200}
                      />
                    )}
                    <br />
                    <strong>UID: </strong>
                    {user?.uid}
                    <br />
                    <strong>Provider Id: </strong>
                    {user?.providerId}
                    <br />
                    <strong>Is Anonymous: </strong>
                    {JSON.stringify(user?.isAnonymous)}
                    <br />
                    <strong>Is Email Verified: </strong>
                    {JSON.stringify(user?.emailVerified)}
                    <br />
                  </div>
                )}
              </>
            </p>
            <button onClick={handleLogout}>Logout</button>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
